/**
 * revisamigrieta.appspot.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Revisamigrietaappspotcom);
  }
}(this, function(expect, Revisamigrietaappspotcom) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Revisamigrietaappspotcom.EstadoDeObra();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('EstadoDeObra', function() {
    it('should create an instance of EstadoDeObra', function() {
      // uncomment below and update the code to test EstadoDeObra
      //var instane = new Revisamigrietaappspotcom.EstadoDeObra();
      //expect(instance).to.be.a(Revisamigrietaappspotcom.EstadoDeObra);
    });

    it('should have the property desplomes (base name: "desplomes")', function() {
      // uncomment below and update the code to test the property desplomes
      //var instane = new Revisamigrietaappspotcom.EstadoDeObra();
      //expect(instance).to.be();
    });

    it('should have the property desprendimiento (base name: "desprendimiento")', function() {
      // uncomment below and update the code to test the property desprendimiento
      //var instane = new Revisamigrietaappspotcom.EstadoDeObra();
      //expect(instance).to.be();
    });

    it('should have the property golpeteo (base name: "golpeteo")', function() {
      // uncomment below and update the code to test the property golpeteo
      //var instane = new Revisamigrietaappspotcom.EstadoDeObra();
      //expect(instance).to.be();
    });

    it('should have the property hundimientos (base name: "hundimientos")', function() {
      // uncomment below and update the code to test the property hundimientos
      //var instane = new Revisamigrietaappspotcom.EstadoDeObra();
      //expect(instance).to.be();
    });

    it('should have the property mas20porciento (base name: "mas20porciento")', function() {
      // uncomment below and update the code to test the property mas20porciento
      //var instane = new Revisamigrietaappspotcom.EstadoDeObra();
      //expect(instance).to.be();
    });

    it('should have the property pisosHuecos (base name: "pisosHuecos")', function() {
      // uncomment below and update the code to test the property pisosHuecos
      //var instane = new Revisamigrietaappspotcom.EstadoDeObra();
      //expect(instance).to.be();
    });

    it('should have the property vibraciones (base name: "vibraciones")', function() {
      // uncomment below and update the code to test the property vibraciones
      //var instane = new Revisamigrietaappspotcom.EstadoDeObra();
      //expect(instance).to.be();
    });

  });

}));
