/**
 * revisamigrieta.appspot.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Revisamigrietaappspotcom);
  }
}(this, function(expect, Revisamigrietaappspotcom) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Revisamigrietaappspotcom.GrietaModel();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GrietaModel', function() {
    it('should create an instance of GrietaModel', function() {
      // uncomment below and update the code to test GrietaModel
      //var instane = new Revisamigrietaappspotcom.GrietaModel();
      //expect(instance).to.be.a(Revisamigrietaappspotcom.GrietaModel);
    });

    it('should have the property comentario (base name: "comentario")', function() {
      // uncomment below and update the code to test the property comentario
      //var instane = new Revisamigrietaappspotcom.GrietaModel();
      //expect(instance).to.be();
    });

    it('should have the property createdOn (base name: "createdOn")', function() {
      // uncomment below and update the code to test the property createdOn
      //var instane = new Revisamigrietaappspotcom.GrietaModel();
      //expect(instance).to.be();
    });

    it('should have the property diagonalesLosa (base name: "diagonalesLosa")', function() {
      // uncomment below and update the code to test the property diagonalesLosa
      //var instane = new Revisamigrietaappspotcom.GrietaModel();
      //expect(instance).to.be();
    });

    it('should have the property diagonalesPiso (base name: "diagonalesPiso")', function() {
      // uncomment below and update the code to test the property diagonalesPiso
      //var instane = new Revisamigrietaappspotcom.GrietaModel();
      //expect(instance).to.be();
    });

    it('should have the property estadoDeObra (base name: "estadoDeObra")', function() {
      // uncomment below and update the code to test the property estadoDeObra
      //var instane = new Revisamigrietaappspotcom.GrietaModel();
      //expect(instance).to.be();
    });

    it('should have the property files (base name: "files")', function() {
      // uncomment below and update the code to test the property files
      //var instane = new Revisamigrietaappspotcom.GrietaModel();
      //expect(instance).to.be();
    });

    it('should have the property geolocalizacion (base name: "geolocalizacion")', function() {
      // uncomment below and update the code to test the property geolocalizacion
      //var instane = new Revisamigrietaappspotcom.GrietaModel();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new Revisamigrietaappspotcom.GrietaModel();
      //expect(instance).to.be();
    });

    it('should have the property modifiedOn (base name: "modifiedOn")', function() {
      // uncomment below and update the code to test the property modifiedOn
      //var instane = new Revisamigrietaappspotcom.GrietaModel();
      //expect(instance).to.be();
    });

    it('should have the property paralelasPiso (base name: "paralelasPiso")', function() {
      // uncomment below and update the code to test the property paralelasPiso
      //var instane = new Revisamigrietaappspotcom.GrietaModel();
      //expect(instance).to.be();
    });

    it('should have the property revisada (base name: "revisada")', function() {
      // uncomment below and update the code to test the property revisada
      //var instane = new Revisamigrietaappspotcom.GrietaModel();
      //expect(instance).to.be();
    });

    it('should have the property tipo (base name: "tipo")', function() {
      // uncomment below and update the code to test the property tipo
      //var instane = new Revisamigrietaappspotcom.GrietaModel();
      //expect(instance).to.be();
    });

    it('should have the property tweet (base name: "tweet")', function() {
      // uncomment below and update the code to test the property tweet
      //var instane = new Revisamigrietaappspotcom.GrietaModel();
      //expect(instance).to.be();
    });

    it('should have the property ubicacionEnum (base name: "ubicacionEnum")', function() {
      // uncomment below and update the code to test the property ubicacionEnum
      //var instane = new Revisamigrietaappspotcom.GrietaModel();
      //expect(instance).to.be();
    });

    it('should have the property userId (base name: "userId")', function() {
      // uncomment below and update the code to test the property userId
      //var instane = new Revisamigrietaappspotcom.GrietaModel();
      //expect(instance).to.be();
    });

  });

}));
