/**
 * revisamigrieta.appspot.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Revisamigrietaappspotcom) {
      root.Revisamigrietaappspotcom = {};
    }
    root.Revisamigrietaappspotcom.EstadoDeObra = factory(root.Revisamigrietaappspotcom.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The EstadoDeObra model module.
   * @module model/EstadoDeObra
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>EstadoDeObra</code>.
   * @alias module:model/EstadoDeObra
   * @class
   */
  var exports = function() {
    var _this = this;








  };

  /**
   * Constructs a <code>EstadoDeObra</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EstadoDeObra} obj Optional instance to populate.
   * @return {module:model/EstadoDeObra} The populated <code>EstadoDeObra</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('desplomes')) {
        obj['desplomes'] = ApiClient.convertToType(data['desplomes'], 'Boolean');
      }
      if (data.hasOwnProperty('desprendimiento')) {
        obj['desprendimiento'] = ApiClient.convertToType(data['desprendimiento'], 'Boolean');
      }
      if (data.hasOwnProperty('golpeteo')) {
        obj['golpeteo'] = ApiClient.convertToType(data['golpeteo'], 'Boolean');
      }
      if (data.hasOwnProperty('hundimientos')) {
        obj['hundimientos'] = ApiClient.convertToType(data['hundimientos'], 'Boolean');
      }
      if (data.hasOwnProperty('mas20porciento')) {
        obj['mas20porciento'] = ApiClient.convertToType(data['mas20porciento'], 'Boolean');
      }
      if (data.hasOwnProperty('pisosHuecos')) {
        obj['pisosHuecos'] = ApiClient.convertToType(data['pisosHuecos'], 'Boolean');
      }
      if (data.hasOwnProperty('vibraciones')) {
        obj['vibraciones'] = ApiClient.convertToType(data['vibraciones'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * @member {Boolean} desplomes
   */
  exports.prototype['desplomes'] = undefined;
  /**
   * @member {Boolean} desprendimiento
   */
  exports.prototype['desprendimiento'] = undefined;
  /**
   * @member {Boolean} golpeteo
   */
  exports.prototype['golpeteo'] = undefined;
  /**
   * @member {Boolean} hundimientos
   */
  exports.prototype['hundimientos'] = undefined;
  /**
   * @member {Boolean} mas20porciento
   */
  exports.prototype['mas20porciento'] = undefined;
  /**
   * @member {Boolean} pisosHuecos
   */
  exports.prototype['pisosHuecos'] = undefined;
  /**
   * @member {Boolean} vibraciones
   */
  exports.prototype['vibraciones'] = undefined;



  return exports;
}));


