/**
 * revisamigrieta.appspot.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/GrietaModel'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./GrietaModel'));
  } else {
    // Browser globals (root is window)
    if (!root.Revisamigrietaappspotcom) {
      root.Revisamigrietaappspotcom = {};
    }
    root.Revisamigrietaappspotcom.RevisionModel = factory(root.Revisamigrietaappspotcom.ApiClient, root.Revisamigrietaappspotcom.GrietaModel);
  }
}(this, function(ApiClient, GrietaModel) {
  'use strict';




  /**
   * The RevisionModel model module.
   * @module model/RevisionModel
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>RevisionModel</code>.
   * @alias module:model/RevisionModel
   * @class
   */
  var exports = function() {
    var _this = this;











  };

  /**
   * Constructs a <code>RevisionModel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RevisionModel} obj Optional instance to populate.
   * @return {module:model/RevisionModel} The populated <code>RevisionModel</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('comentarios')) {
        obj['comentarios'] = ApiClient.convertToType(data['comentarios'], 'String');
      }
      if (data.hasOwnProperty('createdOn')) {
        obj['createdOn'] = ApiClient.convertToType(data['createdOn'], 'Date');
      }
      if (data.hasOwnProperty('diagonalesLosa')) {
        obj['diagonalesLosa'] = ApiClient.convertToType(data['diagonalesLosa'], 'Boolean');
      }
      if (data.hasOwnProperty('diagonalesPiso')) {
        obj['diagonalesPiso'] = ApiClient.convertToType(data['diagonalesPiso'], 'Boolean');
      }
      if (data.hasOwnProperty('grietaModelRef')) {
        obj['grietaModelRef'] = GrietaModel.constructFromObject(data['grietaModelRef']);
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('modifiedOn')) {
        obj['modifiedOn'] = ApiClient.convertToType(data['modifiedOn'], 'Date');
      }
      if (data.hasOwnProperty('paralelasPiso')) {
        obj['paralelasPiso'] = ApiClient.convertToType(data['paralelasPiso'], 'Boolean');
      }
      if (data.hasOwnProperty('peligroInminente')) {
        obj['peligroInminente'] = ApiClient.convertToType(data['peligroInminente'], 'Boolean');
      }
      if (data.hasOwnProperty('revisadaPor')) {
        obj['revisadaPor'] = ApiClient.convertToType(data['revisadaPor'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} comentarios
   */
  exports.prototype['comentarios'] = undefined;
  /**
   * @member {Date} createdOn
   */
  exports.prototype['createdOn'] = undefined;
  /**
   * @member {Boolean} diagonalesLosa
   */
  exports.prototype['diagonalesLosa'] = undefined;
  /**
   * @member {Boolean} diagonalesPiso
   */
  exports.prototype['diagonalesPiso'] = undefined;
  /**
   * @member {module:model/GrietaModel} grietaModelRef
   */
  exports.prototype['grietaModelRef'] = undefined;
  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {Date} modifiedOn
   */
  exports.prototype['modifiedOn'] = undefined;
  /**
   * @member {Boolean} paralelasPiso
   */
  exports.prototype['paralelasPiso'] = undefined;
  /**
   * @member {Boolean} peligroInminente
   */
  exports.prototype['peligroInminente'] = undefined;
  /**
   * @member {String} revisadaPor
   */
  exports.prototype['revisadaPor'] = undefined;



  return exports;
}));


