/**
 * revisamigrieta.appspot.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Revisamigrietaappspotcom) {
      root.Revisamigrietaappspotcom = {};
    }
    root.Revisamigrietaappspotcom.UbicacionEnum = factory(root.Revisamigrietaappspotcom.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';


  /**
   * Enum class UbicacionEnum.
   * @enum {}
   * @readonly
   */
  var exports = {
    /**
     * value: "LOSA"
     * @const
     */
    "LOSA": "LOSA",
    /**
     * value: "PISO"
     * @const
     */
    "PISO": "PISO"  };

  /**
   * Returns a <code>UbicacionEnum</code> enum value from a Javascript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
   * @return {module:model/UbicacionEnum} The enum <code>UbicacionEnum</code> value.
   */
  exports.constructFromObject = function(object) {
    return object;
  }

  return exports;
}));


