/**
 * revisamigrieta.appspot.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/EstadoDeObra', 'model/GeoPt', 'model/GrietaModel', 'model/GrietaModelCollection', 'model/RevisionModel', 'model/RevisionModelCollection', 'model/TipoEnum', 'model/UbicacionEnum', 'api/DefaultApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/EstadoDeObra'), require('./model/GeoPt'), require('./model/GrietaModel'), require('./model/GrietaModelCollection'), require('./model/RevisionModel'), require('./model/RevisionModelCollection'), require('./model/TipoEnum'), require('./model/UbicacionEnum'), require('./api/DefaultApi'));
  }
}(function(ApiClient, EstadoDeObra, GeoPt, GrietaModel, GrietaModelCollection, RevisionModel, RevisionModelCollection, TipoEnum, UbicacionEnum, DefaultApi) {
  'use strict';

  /**
   * ERROR_UNKNOWN.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var Revisamigrietaappspotcom = require('index'); // See note below*.
   * var xxxSvc = new Revisamigrietaappspotcom.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new Revisamigrietaappspotcom.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new Revisamigrietaappspotcom.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new Revisamigrietaappspotcom.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 1.0.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The EstadoDeObra model constructor.
     * @property {module:model/EstadoDeObra}
     */
    EstadoDeObra: EstadoDeObra,
    /**
     * The GeoPt model constructor.
     * @property {module:model/GeoPt}
     */
    GeoPt: GeoPt,
    /**
     * The GrietaModel model constructor.
     * @property {module:model/GrietaModel}
     */
    GrietaModel: GrietaModel,
    /**
     * The GrietaModelCollection model constructor.
     * @property {module:model/GrietaModelCollection}
     */
    GrietaModelCollection: GrietaModelCollection,
    /**
     * The RevisionModel model constructor.
     * @property {module:model/RevisionModel}
     */
    RevisionModel: RevisionModel,
    /**
     * The RevisionModelCollection model constructor.
     * @property {module:model/RevisionModelCollection}
     */
    RevisionModelCollection: RevisionModelCollection,
    /**
     * The TipoEnum model constructor.
     * @property {module:model/TipoEnum}
     */
    TipoEnum: TipoEnum,
    /**
     * The UbicacionEnum model constructor.
     * @property {module:model/UbicacionEnum}
     */
    UbicacionEnum: UbicacionEnum,
    /**
     * The DefaultApi service constructor.
     * @property {module:api/DefaultApi}
     */
    DefaultApi: DefaultApi
  };

  return exports;
}));
